### PR TITLE
SRF tests results view bug fixes

### PR DESCRIPTION
**Pull request by noam123**
- Fixed defect [AGM#39673 | Jira [JENKINS-48704](https://issues.jenkins-ci.org/browse/JENKINS-48704)] Environment title is not match in Jenkins Test Results 
- Fixed defect [AGM#39871 | Jira [JENKINS-48705](https://issues.jenkins-ci.org/browse/JENKINS-48705)] Redundant root level in report view
- Fixed defect [AGM#39872 | Jira [JENKINS-48706](https://issues.jenkins-ci.org/browse/JENKINS-48706)] Cannot correlate script result page in jenkins to SRF script run

### CODE REVIEW

**Comment by YafimK** [comment]
- [ ] Please add license
- [ ] Please add docs to all changed files to support maintainability to future development

**Comment by noamdo** [comment]
Hi

Can you please elaborate on the license addition and by docs you mean java docs right?

Thanks,
Noam


On 27 Dec 2017, at 8:38, Yafim Kazak <notifications@github.com<mailto:notifications@github.com>> wrote:


  *    Please add license
  *    Please add docs to all changed files to support maintainability to future development

**Comment by YafimK** [comment]
Approved for test build

**Comment by noam123** [comment]
@m-seldin is the failed test related to my changes ?

**Pull request merged**
