### PR TITLE
Slim down plugin

### PR DESCRIPTION
**Pull request by basil**
This plugin was bundling a huge number of JARs that are present already in either Jenkins core or other Jenkins plugins. This PR modernizes the build for this plugin and slims down the plugin `.jpi` by excluding JAR files that are present in Jenkins core or other Jenkins plugins.

### CODE REVIEW

**Comment by basil** [comment]
Change in bundled libraries:

```
--- /tmp/old 2022-05-08 16:18:22.060499986 -0700
+++ /tmp/new    2022-05-08 17:02:12.627104643 -0700
@@ -1,48 +1,22 @@
-activation-1.1.1.jar
-annotation-indexer-1.9.jar
-asm-1.0.jar
-asm-3.3.1.jar
+accessors-smart-2.4.7.jar
+annotation-indexer-1.14.jar
 commons-cli-1.3.1.jar
-commons-codec-1.11.jar
 commons-collections4-4.2.jar
 commons-csv-1.8.jar
-commons-httpclient-3.1.jar
-commons-lang-2.6.jar
 commons-lang3-3.12.0.jar
 commons-math3-3.6.1.jar
 gson-2.8.1.jar
 hp-application-automation-tools-plugin.jar
-httpclient-4.5.13.jar
-httpcore-4.4.4.jar
-httpmime-4.5.6.jar
 integrations-dto-2.7.3.7.jar
 integrations-sdk-2.7.3.7.jar
-istack-commons-runtime-4.0.0.jar
-jackson-annotations-2.11.1.jar
-jackson-core-2.11.1.jar
-jackson-databind-2.11.1.jar
-jackson-dataformat-xml-2.10.0.jar
-jackson-dataformat-yaml-2.11.1.jar
-jackson-module-jaxb-annotations-2.10.0.jar
-jakarta.activation-2.0.0.jar
-jakarta.activation-api-1.2.1.jar
-jakarta.xml.bind-api-3.0.0.jar
-javax.activation-api-1.2.0.jar
-jaxb-api-2.3.1.jar
-jaxb-core-3.0.0.jar
-jaxb-runtime-3.0.0.jar
-json-path-1.1.0.jar
-json-smart-2.0.jar
+json-path-2.7.0.jar
+json-smart-2.4.7.jar
 log4j-api-2.17.1.jar
 log4j-core-2.17.1.jar
 log4j-web-2.17.1.jar
 plugins-common-1.1.9.jar
 poi-4.0.1.jar
-snakeyaml-1.26.jar
-stax2-api-4.2.jar
 SVConfigurator-5.5.jar
 symbol-annotation-1.4.jar
 tape-1.2.3.jar
-txw2-3.0.0.jar
-woodstox-core-6.0.1.jar
 zip4j-1.3.3.jar
```

**Comment by basil** [comment]
CC @LauraBuzas @plescaevelyn

**Comment by basil** [comment]
As a gentle reminder, we are planning on requiring Java 11 in the Jenkins weekly release line as of June 21, 2022. Ideally, we would be able to merge and release this PR prior to that date to ensure a smooth experience for users of the weekly release line. The LTS line will require Java 11 beginning in September 2022.

**Comment by dorin7bogdan** [comment]
Hi @basil,
Thank you for your suggested changes.

According to the plugin requirements https://plugins.jenkins.io/hp-application-automation-tools-plugin/:
"This plugin requires one of the five latest LTS versions of Jenkins."
Therefore, is it possible to adjust the PR to support Jenkins 2.277.1 ? 
Also, is this PR compatible with Java 11 ?
Any suggestion is welcome.
Thank you so much.

**Comment by basil** [comment]
> Thank you for your suggested changes.

You are welcome!

> Therefore, is it possible to adjust the PR to support Jenkins 2.277.1 ?

2.346.1 is planned for June 15, 2022, so in two weeks the five most recent LTS lines would be 2.346.x, 2.332.x, 2.319.x, 2.303.x, and 2.289.x. I think your request is throwaway work that will have no purpose in two weeks' time, and I decline to accommodate this request.

> Also, is this PR compatible with Java 11 ?

By virtue of adding an explicit dependency on the JAXB plugin, this PR should improve Java 11 compatibility.

**Pull request merged**
