### PR TITLE
fixing defect https://issues.jenkins-ci.org/browse/JENKINS-49459: New parametrization feature of PC Plugin affects the configuration of the job

### PR DESCRIPTION
**Pull request by danieldanan**
Please Make sure these boxes are checked before submitting your pull request - Thanks ahead!

- [x] Proper pull request title - concise and clear for others.
- [x] Proper pull request short description - clear and concise (as it should appear in the Jira ticket) for other developers and users.
- [x] Proper Jira ticket - Number, Link in pull request description.
- [x] The PR can is merged on your machine without any conflicts.
- [x] The PR can is built on your machine without any (new) warnings.
- [x] The PR passed sanity tests by you / QA / DevTest / Good Samaritain.
- [ ] Add unit tests with new features.
- [ ] If you added any dependency to the POM - Please update @YafimK

### CODE REVIEW

**Comment by YafimK** [comment]
Please write proper descriptive headline and include the jira link in the body.

**Comment by danieldanan** [comment]
Description: Running parametrized job with Performance Center plugin works fine for the first time however it modifies the values in the configuration of the job ( in the job's configuration, the parameters are actually replaced by the values given during first run).

Running once again the same job, will actually cause the job to use the values that were injected in the configuration during the first run and stop considering the parameters

**Comment by danieldanan** [comment]
Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-49459

**Comment by danieldanan** [comment]
I closed the pull request, Yafim is supposed to do that after merging.

**Pull request merged**
