### PR TITLE
UFT improvements

### PR DESCRIPTION
**Pull request by m-seldin**
[UTF Discovery Job does not add to octane localized tests (defect #574013 JENKINS-49765)](https://issues.jenkins-ci.org/browse/JENKINS-JENKINS-49765)
[SVN support for uft inegration JENKINS-49765 userstory #522126](https://issues.jenkins-ci.org/browse/JENKINS-JENKINS-49765)

### CODE REVIEW

**Comment by YafimK** [comment]
Please fix two small codacy issues - 
 Avoid unused imports such as 'hudson.plugins.git.GitChangeSet' 
Method names should not start with capital letters

**Comment by YafimK** [comment]
Approved for test build

**Comment by m-seldin** [comment]
all fixes applied.

**Comment by m-seldin** [comment]
Approved for test build

**Pull request merged**
