### PR TITLE
Octane version 5.3 beta improvments

### PR DESCRIPTION
**Pull request by m-seldin**
* user story #476010 : Improve integration with StormRunnerLoad - add external report
* defect #477085 : Octane-UFT integration : if data table file extension is in upper case - it is not discovered by discovery job
* defect 476068 : localized UFT test cannot be discovered

u.s #450005 - [tech] Collect coverage report of JaCoCo from Jenkins and send them to Octane (+including remote such as slaves) + queue in Jenkins.

[[tech] Collect coverage report of JaCoCo from Jenkins and send them to Octane (JENKINS-47956)](https://issues.jenkins-ci.org/browse/JENKINS-47956)

[Improve integration with StormRunnerLoad  (JENKINS-47831)](https://issues.jenkins-ci.org/browse/JENKINS-47831)

[Let Octane know if tests result are expected for perticular job (JENKINS-47957)](https://issues.jenkins-ci.org/browse/JENKINS-47957)

[Enable/disable reporting from CI server (JENKINS-47995)](https://issues.jenkins-ci.org/browse/JENKINS-47995)

[Handling the reset build id cases (JENKINS-48164) (#Defect 503018)](https://issues.jenkins-ci.org/browse/JENKINS-48164)

suspend octane events doesnt work from the CI (JENKINS-48222) (Defect #505031)

[Change test results submission intervals to  3 sec, 10 sec, 2 minutes (JIRA-48559)(Defect #521009)](https://issues.jenkins-ci.org/browse/JENKINS-48559)

### CODE REVIEW

**Comment by m-seldin** [comment]
approved for test build

**Comment by radislavB** [comment]
@m-seldin please rerun JenkinsCI , seems like previous fail is because of env issues.

**Comment by m-seldin** [comment]
approved for test build

**Comment by YafimK** [comment]
@m-seldin please check conflicts

**Comment by YafimK** [comment]
Approved for test build

**Comment by m-seldin** [comment]
approved for test build

**Comment by m-seldin** [comment]
approved for test build

**Pull request merged**
