### PR TITLE
Issue 44314 add credentials for proxy + Continues Publishing issue 47135

### PR DESCRIPTION
**Pull request by bamh**
* Supporting credentials for proxy.
https://issues.jenkins-ci.org/browse/JENKINS-44314

* Continues publishing issue 
https://issues.jenkins-ci.org/browse/JENKINS-47135

### CODE REVIEW

**Comment by hpsa** [comment]
Approved for test build

**Comment by YafimK** [comment]
Approved for test build

**Comment by YafimK** [comment]
please remove:
org.apache.http.client.HttpClient
'org.apache.http.impl.client.HttpClientBuilder

if they are unused...

**Comment by YafimK** [comment]
Approved for test build

**Comment by YafimK** [comment]
Approved for test build

**Pull request merged**
