### PR TITLE
Support nunit3 format result file parsing and uploading to ALM.

### PR DESCRIPTION
**Pull request by Roy-Lu**
https://issues.jenkins-ci.org/browse/JENKINS-52812

### CODE REVIEW

**Comment by grount** [comment]
Please see https://ci.appveyor.com/project/HPEbot/hp-application-automation-tools-plugin/build/latest.289-pbglvaof

**Comment by Roy-Lu** [comment]
The test maybe never ran before! Can't believe that. It's even not unit test.

**Comment by grount** [comment]
So how it ran as a test?

**Comment by Roy-Lu** [comment]
It's never ran before.

**Pull request closed without merging**
