### PR TITLE
Output authentication point because many issue caused by authenticati…

### PR DESCRIPTION
**Pull request by Roy-Lu**
Output authentication point because many issues caused by authentication point.

### CODE REVIEW

**Comment by grount** [comment]
@Roy-Lu, Is this change part of a JIRA issue?

**Comment by Roy-Lu** [comment]
@grount No, not a JIRA issue.

**Comment by grount** [comment]
@Roy-Lu, Please open a relevant Jira issue, and if it's not critical we shall wait after the release.

**Comment by Roy-Lu** [comment]
@grount . This is just for better debugging. Is this need a JIRA too?

**Comment by grount** [comment]
Approved for test build

**Pull request merged**
