### PR TITLE
Octane improvements and defect fixes for 5.3.5-beta

### PR DESCRIPTION
**Pull request by m-seldin**
[Branch compare](https://issues.jenkins-ci.org/browse/JENKINS-50245)
[UFT SVN Integration - deleted test from existing svn repository are not detected by discovery job.](https://issues.jenkins-ci.org/browse/JENKINS-50425)
[New tests added to existing svn scm repository are detedcted by discovery job but not injected to octane (defect #600010 )](https://issues.jenkins-ci.org/browse/JENKINS-50426)

### CODE REVIEW

**Comment by YafimK** [comment]
Approved for test build

**Comment by YafimK** [comment]
@m-seldin please check local build errors

**Comment by m-seldin** [comment]
Approved for test build

**Comment by YafimK** [comment]
Approved for test build

**Pull request merged**
