### PR TITLE
Client type should have content-type header to work.

### PR DESCRIPTION
**Pull request by Roy-Lu**
Fixed an issue on client type. Client type also need to work with a Content-type header.

### CODE REVIEW

**Comment by grount** [comment]
Please create/add the corresponding JIRA issue.

**Comment by Roy-Lu** [comment]
Already have a JIRA ticket to track the new feature.
https://issues.jenkins-ci.org/browse/JENKINS-51239
As it's an improvement not a story, so I could only leave comment their and keep it open now. I will close it when the issue is solved.

**Comment by grount** [comment]
Is it an improvement or an issue?

**Comment by Roy-Lu** [comment]
Adding client type field is an improvement. But a issue of it was found during 5.5 QA cycle. So I commit this PR to fix it.

**Comment by grount** [comment]
Approved for test build

**Pull request merged**
