### PR TITLE
Moving Octane's part of the plugin to run over Octane CIPlugin SDK

### PR DESCRIPTION
**Pull request by m-seldin**
[Moving the Octane's part of the plugin to run over Octane (JENKINS-49398 UserStory #561086)](https://issues.jenkins-ci.org/browse/JENKINS-49398)

### CODE REVIEW

**Comment by gullerya** [comment]
@YafimK : what are unnecessary changes you are talking about?

**Comment by YafimK** [comment]
to pom

**Comment by m-seldin** [comment]
@YafimK - fixed requested changes

**Comment by YafimK** [comment]
Approved for test build

**Pull request merged**
