### PR TITLE
SRF Bug Fixes

### PR DESCRIPTION
**Pull request by noam123**
- In case the test is stopped via SRF the Jenkins job continue to run 
Jira: https://issues.jenkins-ci.org/browse/JENKINS-49355

-  Second execution fails when running 2 tests with different tags and a space after the comma delimiter
Jira: https://issues.jenkins-ci.org/browse/JENKINS-49356
 
-  Description steps are missing for UFT test result 
Jira: https://issues.jenkins-ci.org/browse/JENKINS-49357

-  Running scripts which finish in 'completed' status marked as failed tests in jerkins's test results with unavailable script steps 
Jira: https://issues.jenkins-ci.org/browse/JENKINS-49358

- Unable to open tests results in case script name contains spaces 
Jira: https://issues.jenkins-ci.org/browse/JENKINS-49360

-  No results nor error message when tunnel doest's exist 
Jira: https://issues.jenkins-ci.org/browse/JENKINS-49360

- Added testrun result to junitresult.xml for Octane Integration

### CODE REVIEW

**Comment by YafimK** [comment]
@noam123 please review the codacy issues and update.

**Comment by noam123** [comment]
@YafimK Fixed Codacy issues

**Comment by YafimK** [comment]
There are still a lot there.

**Comment by noam123** [comment]
@YafimK pushed the rest of the fixes

**Comment by YafimK** [comment]
cool  - waiting for codacy to finish doing it's magic

**Comment by YafimK** [comment]
approved for test build

**Pull request merged**
