### PR TITLE
US-1654874 - [Jenkins][ALM]Security issue check

### PR DESCRIPTION
**Pull request by dorin7bogdan**
https://issues.jenkins.io/browse/SECURITY-3277 
Multiple missing permission checks - ALM job config

### CODE REVIEW

**Review by Kevin-CB — APPROVED** [review]
I tested the 3 web methods locally, and I can confirm that the permission checks work fine on them!

**Comment by dorin7bogdan** [comment]
> I tested the 3 web methods locally, and I can confirm that the permission checks work fine on them!

Hi @Kevin-CB,
How can we test directly the methods without opening the Configure page?
We tried to use this URL pattern:
http://jenkins:8080/job/ALM%20FreeStyle/descriptorByName/com.microfocus.application.automation.tools.run.RunFromAlmBuilder$DescriptorImpl/fillAlmServerNameItems
but it always fails with "page not found" error.

**Comment by dorin7bogdan** [comment]
Hi @andreibangau99,
Please merge this PR.

**Comment by Kevin-CB** [comment]
> We tried to use this URL pattern:
http://jenkins:8080/job/ALM%20FreeStyle/descriptorByName/com.microfocus.application.automation.tools.run.RunFromAlmBuilder$DescriptorImpl/fillAlmServerNameItems

This URL is incorrect, you can reach this endpoint with:
`http://jenkins:8080/job/ALM%20FreeStyle/descriptorByName/com.microfocus.application.automation.tools.run.RunFromAlmBuilder/fillAlmServerNameItems`
and
`http://jenkins:8080/descriptorByName/com.microfocus.application.automation.tools.run.RunFromAlmBuilder/fillAlmServerNameItems`

**Pull request merged**
