### PR TITLE
[JENKINS-64500] Remove the table, tr and td tags from the forms that should not be tables

### PR DESCRIPTION
**Pull request by ironcerocloudbees**
Please Make sure these boxes are checked before submitting your pull request - Thanks ahead!

- [X] Proper pull request title - concise and clear for others.
- [X] Proper pull request short description - clear and concise (as it should appear in the Jira ticket) for other developers and users.
- [X] Proper Jira ticket - Number, Link in pull request description.
- [X] The PR can is merged on your machine without any conflicts.
- [X] The PR can is built on your machine without any (new) warnings.
- [ ] The PR passed sanity tests by you / QA / DevTest / Good Samaritan.
- [ ] Add unit tests with new features.
- [ ] If you added any dependency to the POM - Please update grount

cc: @timja, @fqueiruga, @dariver

### CODE REVIEW

**Comment by fbelzunc** [comment]
@tofanadrian3000 hello, do you think we can do a release to include this change?

**Comment by timja** [comment]
@tofanadrian3000 can this be released? the new LTS is being released tomorrow

**Comment by tofanadrian3000** [comment]
Hey @timja, @fbelzunc , if you want we can release a beta version that will include these changes.
As for an official version, these changes will be included into our next official release, after some testing period, along other changes.

**Comment by oleg-nenashev** [comment]
@tofanadrian3000 the process is up to you. Just keep in mind the plugin is likely to impact configuration pages on the Jenkins LTS version which will be released tomorrow. It would be great to expedite the official release to avoid that

**Comment by tofanadrian3000** [comment]
Hey @oleg-nenashev, ok, thank you for the update

**Pull request merged**
